customer/urls.py
from django.urls import path

from customer.views import *

app_name = 'customer'


urlpatterns = [
    path('', Customers.as_view(), name='list'),
    path('edit/<id>/', Update.as_view(), name='edit'),
    path('<id>/', CustomerDetail.as_view(), name='detail'),
]

moon_distribution/urls.py
from django.contrib import admin
from django.urls import path, include
from users import urls as user_urls
from distributions import urls as dist_urls
from purchases import urls as purch_urls
from users.views import LoginView, LogoutView
from sales import urls as sale_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('users/', include(user_urls, namespace='users')),
    path('dist/', include(dist_urls, namespace='distribution')),
    path('purchases/', include(purch_urls, namespace='purchases')),
    path('sales/', include(sale_urls, namespace='sales')),
    path('customer/', include('customer.urls', namespace='customer')),
]

sales/urls.py
from django.urls import *
from .views import *

app_name = 'sales'


urlpatterns = [
    path('', Sales.as_view(), name='sales'),
    path('add/', NewSalesTemp.as_view(), name='add'),
    # path('add/', NewSale.as_view(), name='add'),
    path('annex/add/', NewSaleRedirect.as_view(), name='add-annex'),
    path('export/<type>/', export, name='export'),
    path('customer/', NewCustomer.as_view(), name='customer'),
]

customer/models.py
from django.db import models

# Create your models here.

customer/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import *

from distributions.models import Customer


class Customers(LoginRequiredMixin, ListView):
    template_name = 'customer/index.html'
    queryset = Customer.objects.all()


class CustomerDetail(LoginRequiredMixin, DetailView):
    template_name = 'customer/details.html'
    queryset = Customer.objects.all()
    pk_url_kwarg = 'id'


class Update(LoginRequiredMixin, RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse_lazy('customer:detail', kwargs={'id': self.kwargs.get('id')})

    def post(self, request, *args, **kwargs):
        full_name = request.POST.get('full_name')
        contact = request.POST.get('contact')

        customer = Customer.objects.get(id=self.kwargs.get('id'))

        customer.full_name = full_name
        customer.contact = contact
        customer.save()

        return super(Update, self).post(self, request, *args, **kwargs)

templates/customer/details.html
{% extends 'base.html' %}
{% block cus1 %}
active
{% endblock %}
{% block cus %}
active
{% endblock %}
{% block title %}
{{ object.full_name }} {{ block.super }}
{% endblock %}
{% block page %}
{{ object.full_name }}
{% endblock %}
{% block header %}
{#    <a href="" class="btn btn-secondary btn-lg"><span class="ni ni-fat-add"></span> New Customer</a>#}
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-xl-12 mb-5 mb-xl-0">
            <div class="card bg-gradient-secondary shadow">

                <div class="card-header bg-white">
                    <div class="row">
                        <div class="col-md-6">
                            <span class="card-title">Details</span>
                        </div>
                        <div class="col-md-6" align="right">
                            Sales
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <form action="{% url 'customer:edit' object.id %}" method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <input type="text" name="full_name" value="{{ object.full_name }}" placeholder="Full Name" class="form-control">
                                </div>
                                <div class="form-group">
                                    <input type="text" name="contact" value="{{ object.contact }}" placeholder="Contact" class="form-control">
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn-block btn-sm btn-github">Save</button>
                                </div>
                            </form>
                        </div>
                        <div class="col-md-6">
                            <div class="list-group">
                                {% for sale in object.sales.all %}

                                    <div class="list-group-item">
                                        <div class="row">
                                            <div class="col-md-6">{{ sale.product }}</div>
                                            <div class="col-md-6" align="right">GHS {{ sale.amount }}</div>
                                        </div>
                                    </div>


                                {% endfor %}

                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

templates/customer/index.html
{% extends 'base.html' %}
{% block cus1 %}
active
{% endblock %}
{% block cus %}
active
{% endblock %}
{% block title %}
Customers {{ block.super }}
{% endblock %}
{% block page %}
Customers
{% endblock %}
{% block header %}
    <a href="" class="btn btn-secondary btn-lg"><span class="ni ni-fat-add"></span> New Customer</a>
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-xl-12 mb-5 mb-xl-0">
            <div class="card bg-gradient-secondary shadow">

                <div class="card-header bg-white">
                    <div class="row">
                        <div class="col-md-6">
                            <span class="card-title">Customers</span>
                        </div>
{#                        <div class="col-md-6" align="right">#}
{#                            <a href="{% url 'sales:export' 'csv' %}" class="btn btn-sm btn-slack">CSV</a>#}
{#                            <a href="{% url 'sales:export' 'xls' %}" class="btn btn-sm btn-twitter">XLS</a>#}
{#                        </div>#}
                    </div>
                </div>
                <div class="card-body">
                    <div class="list-group">
                        {% for object in object_list %}
                            <div class="list-group-item">
                                <a href="{% url 'customer:detail' object.id %}">
                                    <div class="row">
                                        <div class="col-md-6">{{ object.full_name }}</div>
                                        <div class="col-md-6" align="right"><small class="small">{{ object.sales.count }} Sales</small></div>
                                    </div>
                                </a>
                            </div>
                        {% endfor %}

                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}