moon_distribution/urls.py
from django.contrib import admin
from django.urls import path, include
from users import urls as user_urls
from distributions import urls as dist_urls
from purchases import urls as purch_urls
from users.views import LoginView, LogoutView
from sales import urls as sale_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('users/', include(user_urls, namespace='users')),
    path('dist/', include(dist_urls, namespace='distribution')),
    path('purchases/', include(purch_urls, namespace='purchases')),
    path('sales/', include(sale_urls, namespace='sales')),
    path('customer/', include('customer.urls', namespace='customer')),
]

sales/urls.py
from django.urls import *
from .views import *

app_name = 'sales'


urlpatterns = [
    path('', Sales.as_view(), name='sales'),
    path('add/', NewSalesTemp.as_view(), name='add'),
    # path('add/', NewSale.as_view(), name='add'),
    path('annex/add/', NewSaleRedirect.as_view(), name='add-annex'),
    path('export/<type>/', export, name='export'),
    path('customer/', NewCustomer.as_view(), name='customer'),
]

distributions/forms/sale.py
from django.forms import *
from ..models import *


class SalesForm(ModelForm):
    errors = {
        'quantity_error': 'The quantity entered is more than available in stock'
    }

    class Meta:
        model = Sale
        fields = ('product', 'quantity', 'unit_quantity_price', 'amount', 'customer')
        # exclude = ('id', 'sale_id', 'sale_at', 'recorded_by',)
        widgets = {
            'product': Select(attrs={'required': True}),
            'quantity': NumberInput(attrs={'required': True}),
            'unit_quantity_price': NumberInput(attrs={'required': True}),
            'amount': NumberInput(attrs={'required': True}),
            'customer_name': TextInput(attrs={'required': True}),
            'customer_contact': NumberInput(attrs={'required': True})
        }

    def clean(self):
        quantity = self.cleaned_data.get('quantity')
        product = self.cleaned_data.get('product')
        stocks = Stock.objects.filter(product=product)
        for stock in stocks:
            if quantity > stock.quantity:
                raise ValidationError(
                    self.errors['quantity_error'],
                    code='quantity_error',
                )
        return quantity

sales/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, HttpResponse
from django.utils import timezone
from django.views.generic import *
from django.urls import *
from distributions.forms.sale import *
from distributions.models import Sale, Stock, Product
import csv, xlwt


class Sales(LoginRequiredMixin, ListView):
    template_name = 'sales/index.html'
    queryset = Sale.objects.all()


class NewSalesTemp(LoginRequiredMixin, TemplateView):
    template_name = 'sales/new.html'

    def get_context_data(self, **kwargs):
        context = super(NewSalesTemp, self).get_context_data(**kwargs)
        context['products'] = Product.objects.all()
        context['customers'] = Customer.objects.all()
        return context

# class NewSale(LoginRequiredMixin, CreateView):
#     template_name = 'sales/new.html'
#     form_class = SalesForm
#     success_url = '/sales/'
#
#     def form_valid(self, form):
#         valid = super(NewSale, self).form_valid(form)
#         form.instance.recorded_by = self.request.user
#         # form.instance.sale_at = timezone.now()
#         stock = Stock.objects.get(product_id=form.instance.product.id)
#         product = Product.objects.get(product_id=form.instance.product.id)
#         stock.sold += form.instance.quantity
#         stock.quantity = stock.quantity - form.instance.quantity
#         product.sales.add(form.instance)
#         product.quantity = stock.quantity - form.instance.quantity
#
#         product.save()
#         stock.save()
#         form.save()
#         return valid
    
    
class NewSaleRedirect(LoginRequiredMixin, RedirectView):
    url = None
    
    def post(self, request, *args, **kwargs):
        product_id = request.POST.get('product')
        customer = request.POST.get('customer')
        # customer_contact = request.POST.get('customer_contact')
        quantity = request.POST.get('quantity')
        unit_quantity_price = request.POST.get('unit_quantity_price')
        # amount = request.POST.get('amount')

        stock = Stock.objects.get(product_id=product_id)
        product = Product.objects.get(id=product_id)

        if not int(quantity) > stock.quantity:
            amount = int(quantity) * int(unit_quantity_price)
            sale = Sale.objects.create(
                product_id=product_id,
                customer_id=customer,
                # customer_name=customer_name,
                quantity=quantity,
                unit_quantity_price=unit_quantity_price,
                amount=amount,
                recorded_by=self.request.user
            )
            stock.sold += int(sale.quantity)
            stock.quantity = stock.quantity - int(sale.quantity)
            if stock.quantity == 0:
                stock.status = 2
            product.sales.add(sale)
            custome = Customer.objects.get(id=customer)
            custome.sales.add(sale)
            product.sales_total += sale.amount
            product.profit_loss = product.sales_total - product.purchases_total
            product.revenue = product.revenue + sale.amount
            product.save()
            stock.save()
            sale.save()
            self.url = reverse_lazy('sales:sales')
            return super(NewSaleRedirect, self).post(self, request, *args, **kwargs)
        else:
            messages.error(request, 'Quantity is more than stock of product')
            return HttpResponseRedirect(reverse_lazy('sales:add'))


class NewCustomer(LoginRequiredMixin, RedirectView):
    url = reverse_lazy('sales:add')

    def post(self, request, *args, **kwargs):
        full_name = request.POST.get('full_name')
        contact = request.POST.get('contact')

        customer = Customer.objects.create(
            full_name=full_name,
            contact=contact,
            created_by=self.request.user,
        )
        customer.save()

        return super(NewCustomer, self).post(self, request, *args, **kwargs)

# class NewSaleAnnex(LoginRequiredMixin, CreateView):
#     template_name = 'sales/new.html'
#     form_class = SalesForm
#     success_url = reverse_lazy('purchases:purchases')
#
#     # def form_valid(self, form):
#     #     valid = super(NewSaleAnnex, self).form_valid(form)
#     #     form.instance.recorded_by = self.request.user
#     #     # form.instance.sale_at = timezone.now()
#     #     stock = Stock.objects.get(product_id=form.instance.product.id)
#     #     product = Product.objects.get(product_id=form.instance.product.id)
#     #     stock.sold += form.instance.quantity
#     #     stock.quantity = stock.quantity - form.instance.quantity
#     #     product.sales.add(form.instance)
#     #     product.quantity = stock.quantity - form.instance.quantity
#     #
#     #     product.save()
#     #     stock.save()
#     #     form.save()
#     #     return valid


def export(request, **kwargs):
    type = kwargs.get('type')

    if type == 'csv':
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="sales.csv"'

        writer = csv.writer(response)
        writer.writerow(['Sale ID', 'Product', 'Customer Name', 'Customer Contact', 'Quantity', 'Unit Price', 'Total Amount', 'Recorded Date', 'Recorded By'])

        sales = Sale.objects.all()
        for sale in sales:
            writer.writerow([sale.sale_id, sale.product.product_name, sale.customer.full_name, sale.customer.contact, sale.quantity, sale.unit_quantity_price, sale.amount, sale.sale_at, sale.recorded_by.get_full_name()])
        return response
    elif type == 'xls':
        response = HttpResponse(content_type='application/ms-excel')
        response['Content-Disposition'] = 'attachment; filename="sales.xls"'

        wb = xlwt.Workbook(encoding='utf-8')
        ws = wb.add_sheet('Sales')
        row_num = 0

        font_style = xlwt.XFStyle()
        font_style.font.bold = True

        columns = ['Sale ID', 'Product', 'Customer Name', 'Customer Contact', 'Quantity', 'Unit Price', 'Total Amount', 'Recorded Date', 'Recorded By']

        for col in range(len(columns)):
            ws.write(row_num, col, columns[col], font_style)

        font_style = xlwt.XFStyle()

        rows = Sale.objects.all()
        for row in rows:
            row_num += 1
            selected = [row.sale_id, row.product.product_name, row.customer.full_name, row.customer.contact, row.quantity, row.unit_quantity_price, row.amount, f'{row.sale_at.date()} {row.sale_at.time()}', row.recorded_by.get_full_name()]
            for col in range(len(selected)):
                ws.write(row_num, col, selected[col], font_style)

        wb.save(response)
        return response

templates/sales/index.html
{% extends 'base.html' %}
{% block sal1 %}
active
{% endblock %}
{% block sal %}
active
{% endblock %}
{% block title %}
Sales {{ block.super }}
{% endblock %}
{% block page %}
Sales
{% endblock %}
{% block header %}
    <a href="{% url 'sales:add' %}" class="btn btn-secondary btn-lg"><span class="ni ni-fat-add"></span> New Sale</a>
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-xl-12 mb-5 mb-xl-0">
            <div class="card bg-gradient-secondary shadow">

                <div class="card-header bg-white">
                    <div class="row">
                        <div class="col-md-6">
                            <span class="card-title">Sales</span>
                        </div>
                        <div class="col-md-6" align="right">
                            <a href="{% url 'sales:export' 'csv' %}" class="btn btn-sm btn-slack">CSV</a>
                            <a href="{% url 'sales:export' 'xls' %}" class="btn btn-sm btn-twitter">XLS</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <div>
                            <table class="table align-items-center">
                                <thead class="thead-light">
                                <tr class="text-center">
                                    <th scope="col">Sale ID</th>
                                    <th scope="col">
                                        Product
                                    </th>
                                    {#                                <th scope="col">#}
                                    {#                                    Brand#}
                                    {#                                </th>#}
                                    <th scope="col">
                                        Customer Name
                                    </th>
                                    <th scope="col">Customer Contact</th>
                                    <th scope="col">
                                        Quantity
                                    </th>
                                    <th scope="col">Unit Price</th>
                                    <th>Total Amount</th>
                                    {#                                <th>Supplier</th>#}
                                </tr>
                                </thead>
                                <tbody class="list">
                                {% for sale in object_list %}
                                    <tr class="text-center">
                                        <th>{{ sale.sale_id }}</th>
                                        <td scope="row" class="name">
                                            {{ sale.product }}
                                        </td>
                                        <td class="budget">
                                            {{ sale.customer.full_name }}
                                        </td>
                                        <td class="status">
                                            {{ sale.customer.contact }}
                                        </td>
                                        <td>
                                            {% if sale.quantity %}{{ sale.quantity }}{% else %}0{% endif %}
                                        </td>
                                        <td class="completion">
                                            {% if sale.unit_quantity_price %}{{ sale.unit_quantity_price }}{% else %}0{% endif %}
                                        </td>
                                        <td >
                                            {{ sale.amount }}
                                        </td>
                                        {#                                    <td >#}
                                        {#                                        {{ sale.supplier }}#}
                                        {#                                    </td>#}
                                    </tr>
                                {% endfor %}


                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

templates/sales/new.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block sal1 %}
active
{% endblock %}
{% block sal %}
active
{% endblock %}
{% block title %}
New Sale {{ block.super }}
{% endblock %}
{% block page %}
New Sale
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-xl-6">
            <div class="card bg-gradient-neutral shadow">
                <div class="card-body">
                    <form method="post" action="{% url 'sales:add-annex' %}">
                        {% csrf_token %}
                        {% if messages %}{% for message in messages %}<span class="error text-danger">{{ message|safe }}</span>{% endfor %}{% endif %}
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-11">
                                    <select class="form-control" required name="customer">
                                        <option value="">Select a customer</option>
                                        {% for customer in customers %}
                                            <option value="{{ customer.id }}">{{ customer.full_name }}</option>
                                        {% endfor %}

                                    </select>
                                </div>
                                <div class="col-md-1">
                                    <a href="#" class="btn btn-sm btn-secondary" data-toggle="modal" data-target="#customer" title="New Customer"><span class="fa fa-plus"></span></a>
                                </div>
                            </div>

                        </div>

                        <div class="form-group">
                            <select class="form-control" name="product">
                                <option value="">Select a Product</option>
                                {% for product in products %}
                                    <option value="{{ product.id }}">{{ product.product_name }}</option>
                                {% endfor %}
                            </select>
                        </div>

                        <div class="form-group">
                            <input type="number" name="quantity" class="form-control" placeholder="Quantity">
                        </div>
                        <div class="form-group">
                            <input type="number" name="unit_quantity_price" class="form-control" placeholder="Unit Quantity Price in GHS">
                        </div>
{#                        <div class="form-group">#}
{#                            <input type="number" name="amount" class="form-control" placeholder="Amount in GHS">#}
{#                        </div>#}
{#                        <div class="form-group">#}
{#                            <input type="text" name="customer_name" class="form-control" placeholder="Customer Name">#}
{#                        </div>#}
{#                        <div class="form-group">#}
{#                            <input type="text" name="customer_contact" class="form-control" placeholder="Customer Contact">#}
{#                        </div>#}
                        <div class="form-group mr-2 ml-2">
                            <button type="submit" class="btn btn-success btn-block">Save</button>
                        </div>
                    </form>
                </div>


            </div>
        </div>
    </div>
    <div class="modal fade" id="customer" tabindex="-1" role="dialog" aria-labelledby="customer" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-body p-0">
                    <div class="card bg-secondary shadow border-0">
                        <div class="card-header bg-transparent pb-5">
                            <div class="text-muted text-center mt-2 mb-3"><small>New Customer</small></div>
                        </div>
                        <div class="card-body px-lg-5 py-lg-5">
                            <form role="form" action="{% url 'sales:customer' %}" method="post">
                                {% csrf_token %}
                                <div class="form-group mb-3">
                                    <div class="input-group input-group-alternative">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text"><i class="ni ni-email-83"></i></span>
                                        </div>
                                        <input class="form-control" name="full_name" placeholder="Full Name" type="text">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="input-group input-group-alternative">
                                        <div class="input-group-prepend">
                                            <span class="input-group-text"><i class="ni ni-lock-circle-open"></i></span>
                                        </div>
                                        <input class="form-control" name="contact" placeholder="Contact" type="text">
                                    </div>
                                </div>
                                <div class="text-center">
                                    <button type="submit" class="btn btn-primary my-4">Submit</button>
                                </div>
                            </form>
                        </div>
                    </div>

                </div>

            </div>
        </div>
    </div>

{% endblock %}