customer/urls.py
from django.urls import path

from customer.views import *

app_name = 'customer'


urlpatterns = [
    path('', Customers.as_view(), name='list'),
    path('edit/<id>/', Update.as_view(), name='edit'),
    path('<id>/', CustomerDetail.as_view(), name='detail'),
]

distributions/urls.py
from django.urls import *
from .views import *

app_name = 'distribution'


urlpatterns = [
    path('stock/', Stocks.as_view(), name='stocks'),
    path('product/new/', NewProduct.as_view(), name='product-new'),
    path('transact/<id>/', Transaction.as_view(), name='transact'),
]

moon_distribution/urls.py
from django.contrib import admin
from django.urls import path, include
from users import urls as user_urls
from distributions import urls as dist_urls
from purchases import urls as purch_urls
from users.views import LoginView, LogoutView
from sales import urls as sale_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('users/', include(user_urls, namespace='users')),
    path('dist/', include(dist_urls, namespace='distribution')),
    path('purchases/', include(purch_urls, namespace='purchases')),
    path('sales/', include(sale_urls, namespace='sales')),
    path('customer/', include('customer.urls', namespace='customer')),
]

purchases/urls.py
from django.urls import *
from .views import *

app_name = 'purchases'


urlpatterns = [
    path('', Purchases.as_view(), name='purchases'),
    path('add/', NewPurchase.as_view(), name='add'),
]

sales/urls.py
from django.urls import *
from .views import *

app_name = 'sales'


urlpatterns = [
    path('', Sales.as_view(), name='sales'),
    path('add/', NewSalesTemp.as_view(), name='add'),
    # path('add/', NewSale.as_view(), name='add'),
    path('annex/add/', NewSaleRedirect.as_view(), name='add-annex'),
    path('export/<type>/', export, name='export'),
    path('customer/', NewCustomer.as_view(), name='customer'),
]

users/urls.py
from django.urls import *
from .views import *

app_name = 'users'

urlpatterns = [
    path('dashboard/', Dashboard.as_view(), name='dashboard'),
]

templates/base.html
{% load static %}
<!--

=========================================================
* Argon Dashboard - v1.1.0
=========================================================

* Product Page: https://www.creative-tim.com/product/argon-dashboard
* Copyright 2019 Creative Tim (https://www.creative-tim.com)
* Licensed under MIT (https://github.com/creativetimofficial/argon-dashboard/blob/master/LICENSE.md)

* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software. -->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
        {% block title %}
            - Sales and Service Software
        {% endblock %}
    </title>
    <!-- Favicon -->
    <link href="{% static 'img/brand/favicon.png' %}" rel="icon" type="image/png">
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <!-- Icons -->
    <link href="{% static 'js/plugins/nucleo/css/nucleo.css' %}" rel="stylesheet" />
    <link href="{% static 'js/plugins/@fortawesome/fontawesome-free/css/all.min.css' %}" rel="stylesheet" />
    <!-- CSS Files -->
    <link href="{% static 'css/argon-dashboard.css' %}" rel="stylesheet" />
</head>

<body class="">
<nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-white" id="sidenav-main">
    <div class="container-fluid">
        <!-- Toggler -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Brand -->
        <a class="navbar-brand pt-0" href="">
            S & S Software
        </a>
        <!-- User -->
        <ul class="nav align-items-center d-md-none">
            <li class="nav-item dropdown">
                <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <div class="media align-items-center">
                      <span>
                        Jess
                      </span>
                    </div>
                </a>
                <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
                    <div class=" dropdown-header noti-title">
                        <h6 class="text-overflow m-0">Welcome!</h6>
                    </div>
                    <a href="" class="dropdown-item">
                        <i class="ni ni-single-02"></i>
                        <span>My Profile</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="" class="dropdown-item">
                        <i class="ni ni-user-run"></i>
                        <span>Logout</span>
                    </a>
                </div>
            </li>
        </ul>
        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="sidenav-collapse-main">
            <!-- Collapse header -->
            <div class="navbar-collapse-header d-md-none">
                <div class="row">
                    <div class="col-6 collapse-brand">
                        <a href="./index.html">
{#                            <img src="./assets/img/brand/blue.png">#}
                        </a>
                    </div>
                    <div class="col-6 collapse-close">
                        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                            <span></span>
                            <span></span>
                        </button>
                    </div>
                </div>
            </div>
            <!-- Form -->
            <!-- Navigation -->
            <ul class="navbar-nav">
                <li class="nav-item {% block dash %} {% endblock %}">
                    <a class=" nav-link {% block dash1 %} {% endblock %}" href="{% url 'users:dashboard' %}"> <i class="ni ni-tv-2 text-primary"></i> Dashboard
                    </a>
                </li>
                <li class="nav-item {% block pur %}{% endblock %}">
                    <a class="nav-link {% block pur1 %}{% endblock %}" href="{% url 'purchases:purchases' %}">
                        <i class="ni ni-planet text-blue"></i> Purchases
                    </a>
                </li>
                <li class="nav-item {% block sal %} {% endblock %}">
                    <a class="nav-link {% block sal1 %} {% endblock %}" href="{% url 'sales:sales' %}">
                        <i class="ni ni-pin-3 text-orange"></i> Sales
                    </a>
                </li>
                <li class="nav-item {% block sto %} {% endblock %}">
                    <a class="nav-link {% block sto1 %} {% endblock %}" href="{% url 'distribution:stocks' %}">
                        <i class="ni ni-single-02 text-yellow"></i> Stock
                    </a>
                </li>
                <li class="nav-item {% block cus %} {% endblock %}">
                    <a class="nav-link {% block cus1 %} {% endblock %}" href="{% url 'customer:list' %}">
                        <i class="ni ni-diamond text-pink"></i> Customers
                    </a>
                </li>
                <li class="nav-item {% block fin %} {% endblock %}">
                    <a class="nav-link {% block fin1 %} {% endblock %}" href="{% url 'distribution:transact' 'gen' %}">
                        <i class="ni ni-money-coins text-yellow"></i> Transactions
                    </a>
                </li>
                <li class="nav-item {% block set %} {% endblock %}">
                    <a class="nav-link {% block set1 %} {% endblock %}" href="">
                        <i class="ni ni-bullet-list-67 text-red"></i> Settings
                    </a>
                </li>
            </ul>
            <!-- Divider -->
            <hr class="my-3">
            <!-- Heading -->
        </div>
    </div>
</nav>
<div class="main-content">
    <!-- Navbar -->
    <nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
        <div class="container-fluid">
            <!-- Brand -->
            <a class="h4 mb-0 text-white text-uppercase d-none d-lg-inline-block">{% block page %}{% endblock %}</a>
            <!-- Form -->
            <!-- User -->
            <ul class="navbar-nav align-items-center d-none d-md-flex">
                <li class="nav-item dropdown">
                    <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <div class="media align-items-center">
                        <div class="media-body ml-2 d-none d-lg-block">
                            <span class="mb-0 text-sm  font-weight-bold">Jessica Jones</span>
                        </div>
                        </div>
                    </a>
                    <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
                        <div class=" dropdown-header noti-title">
                            <h6 class="text-overflow m-0">Welcome!</h6>
                        </div>
                        <a href="" class="dropdown-item">
                            <i class="ni ni-single-02"></i>
                            <span>My profile</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="{% url 'logout' %}" class="dropdown-item">
                            <i class="ni ni-user-run"></i>
                            <span>Logout</span>
                        </a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
    <!-- End Navbar -->
    <!-- Header -->
    <div class="header bg-gradient-primary pb-8 pt-5 pt-md-8">
        <div class="container-fluid">
            <div class="header-body">
                {% block header %}

                {% endblock %}

            </div>
        </div>
    </div>
    <div class="container-fluid mt--7">
        {% block content %}

        {% endblock %}

        <!-- Footer -->
        <footer class="footer">
            <div class="row align-items-center justify-content-xl-between">
                <div class="col-xl-6">
                    <div class="copyright text-center text-xl-left text-muted">
                        &copy; 2020 <a href="" class="font-weight-bold ml-1">Moon Technologies</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>
</div>
<!--   Core   -->
<script src="{% static 'js/plugins/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'js/plugins/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
<!--   Optional JS   -->
<script src="{% static 'js/plugins/chart.js/dist/Chart.min.js' %}"></script>
<script src="{% static 'js/plugins/chart.js/dist/Chart.extension.js' %}"></script>
<!--   Argon JS   -->
<script src="{% static 'js/argon-dashboard.min.js' %}"></script>
{#<script src="https://cdn.trackjs.com/agent/v3/latest/t.js"></script>#}

</body>

</html>