distributions/urls.py
from django.urls import *
from .views import *

app_name = 'distribution'


urlpatterns = [
    path('stock/', Stocks.as_view(), name='stocks'),
    path('product/new/', NewProduct.as_view(), name='product-new'),
    path('transact/<id>/', Transaction.as_view(), name='transact'),
]

moon_distribution/urls.py
from django.contrib import admin
from django.urls import path, include
from users import urls as user_urls
from distributions import urls as dist_urls
from purchases import urls as purch_urls
from users.views import LoginView, LogoutView
from sales import urls as sale_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('users/', include(user_urls, namespace='users')),
    path('dist/', include(dist_urls, namespace='distribution')),
    path('purchases/', include(purch_urls, namespace='purchases')),
    path('sales/', include(sale_urls, namespace='sales')),
    path('customer/', include('customer.urls', namespace='customer')),
]

sales/urls.py
from django.urls import *
from .views import *

app_name = 'sales'


urlpatterns = [
    path('', Sales.as_view(), name='sales'),
    path('add/', NewSalesTemp.as_view(), name='add'),
    # path('add/', NewSale.as_view(), name='add'),
    path('annex/add/', NewSaleRedirect.as_view(), name='add-annex'),
    path('export/<type>/', export, name='export'),
    path('customer/', NewCustomer.as_view(), name='customer'),
]

templates/stock/index.html
{% extends 'base.html' %}
{% block sto %}
active
{% endblock %}
{% block sto1 %}
active
{% endblock %}
{% block title %}
Stocks {{ block.super }}
{% endblock %}
{% block page %}
Stocks
{% endblock %}
{% block header %}
    <a href="{% url 'distribution:product-new' %}" class="btn btn-secondary btn-lg"><span class="ni ni-fat-add"></span> New Product</a>
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-xl-12 mb-5 mb-xl-0">
            <div class="card bg-gradient-neutral shadow">
                <div class="table-responsive">
                    <div>
                        <table class="table align-items-center">
                            <thead class="thead-light">
                            <tr class="text-center">
                                <th scope="col">Stock ID</th>
                                <th scope="col">
                                    Product
                                </th>
                                <th scope="col">
                                    Brand
                                </th>
                                <th scope="col">
                                    Purchased
                                </th>
                                <th scope="col">Sold</th>
                                <th scope="col">
                                    In Stock
                                </th>
                                <th scope="col">Status</th>
                            </tr>
                            </thead>
                            <tbody class="list">
                            {% for stock in object_list %}
                                <tr class="text-center">
                                    <th>{{ stock.stock_id }}</th>
                                    <td scope="row" class="name">
                                        {{ stock.product }}
                                    </td>
                                    <td class="budget">
                                        {{ stock.product.brand }}
                                    </td>
                                    <td class="status">
                                        {% if stock.purchased %}{{ stock.purchased }}{% else %}0{% endif %}
                                    </td>
                                    <td>
                                        {% if stock.sold %}{{ stock.sold }}{% else %}0{% endif %}
                                    </td>
                                    <td class="completion">
                                        {% if stock.quantity %}{{ stock.quantity }}{% else %}0{% endif %}
                                    </td>
                                    <td >
                                        {{ stock.get_status_display }}
                                    </td>
                                </tr>
                            {% endfor %}


                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>

{% endblock %}